# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "add_numbers": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Susheel-SI.github.io/Test/"

git_url = "https://github.com/Susheel-SI/Test/tree/main/"

def custom_doc_links(name): return None
